import { ClientType } from '../TodayModule/TodayModule';

export const clients: ClientType[] = [
  {
    imgPath: ['/mocks/visitor2.png', '/mocks/small.png', '/mocks/small2.png'],
    name: '1Станиславов Станислав',
    status: 'moon',
    coincidentIds: [],
    id: '1',
    visits: [{ date: new Date('2022, 10, 25') }, { date: new Date('2022, 10, 25') }],
    exises: [
      {
        date: new Date('2022, 8, 23'),
        text: '1Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '1',
      },
      {
        date: new Date('2022, 9, 24'),
        text: '2Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '2',
      },
      {
        date: new Date('2022, 9, 25'),
        text: '3Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '3',
      },
      {
        date: new Date('2022, 9, 26'),
        text: '4Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '4',
      },
      {
        date: new Date('2022, 9, 27'),
        text: '5Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '5',
      },
    ],
    pinnedExisId: '3',
    bills: [10, 20, 200],
    phoneNumber: '+375441234567',
  },
  {
    imgPath: ['/mocks/visitor2.png', '/mocks/small.png', '/mocks/small2.png'],
    name: '1Станиславов Станислав',
    status: 'moon',
    coincidentIds: [],
    id: '2',
    visits: [],
    exises: [
      {
        date: new Date('2022, 8, 23'),
        text: '1Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '1',
      },
      {
        date: new Date('2022, 9, 24'),
        text: '2Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '2',
      },
      {
        date: new Date('2022, 9, 25'),
        text: '3Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '3',
      },
      {
        date: new Date('2022, 9, 26'),
        text: '4Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '4',
      },
      {
        date: new Date('2022, 9, 27'),
        text: '5Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '5',
      },
    ],
    pinnedExisId: '3',
    bills: [10, 20],
    phoneNumber: '+375441234567',
  },
  {
    imgPath: ['/mocks/visitor2.png', '/mocks/small.png', '/mocks/small2.png'],
    name: '1Станиславов Станислав',
    status: 'moon',
    coincidentIds: [],
    id: '3',
    visits: [],
    exises: [
      {
        date: new Date('2022, 8, 23'),
        text: '1Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '1',
      },
      {
        date: new Date('2022, 9, 24'),
        text: '2Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '2',
      },
      {
        date: new Date('2022, 9, 25'),
        text: '3Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '3',
      },
      {
        date: new Date('2022, 9, 26'),
        text: '4Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '4',
      },
      {
        date: new Date('2022, 9, 27'),
        text: '5Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '5',
      },
    ],
    pinnedExisId: '3',
    bills: [10, 20],
    phoneNumber: '+375441234567',
  },
  {
    imgPath: ['/mocks/visitor2.png', '/mocks/small.png', '/mocks/small2.png'],
    name: '1Станиславов Станислав',
    status: 'moon',
    coincidentIds: [],
    id: '4',
    visits: [],
    exises: [
      {
        date: new Date('2022, 8, 23'),
        text: '1Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '1',
      },
      {
        date: new Date('2022, 9, 24'),
        text: '2Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '2',
      },
      {
        date: new Date('2022, 9, 25'),
        text: '3Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '3',
      },
      {
        date: new Date('2022, 9, 26'),
        text: '4Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '4',
      },
      {
        date: new Date('2022, 9, 27'),
        text: '5Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '5',
      },
    ],
    pinnedExisId: '3',
    bills: [10, 20],
    phoneNumber: '+375441234567',
  },
  {
    imgPath: ['/mocks/visitor2.png', '/mocks/small.png', '/mocks/small2.png'],
    name: '1Станиславов Станислав',
    status: 'moon',
    coincidentIds: [],
    id: '5',
    visits: [],
    exises: [
      {
        date: new Date('2022, 8, 23'),
        text: '1Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '1',
      },
      {
        date: new Date('2022, 9, 24'),
        text: '2Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '2',
      },
      {
        date: new Date('2022, 9, 25'),
        text: '3Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '3',
      },
      {
        date: new Date('2022, 9, 26'),
        text: '4Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '4',
      },
      {
        date: new Date('2022, 9, 27'),
        text: '5Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '5',
      },
    ],
    pinnedExisId: '3',
    bills: [10, 20],
    phoneNumber: '+375441234567',
  },
  {
    imgPath: ['/mocks/visitor2.png', '/mocks/small.png', '/mocks/small2.png'],
    name: '1Станиславов Станислав',
    status: 'moon',
    coincidentIds: [],
    id: '6',
    visits: [],
    exises: [
      {
        date: new Date('2022, 8, 23'),
        text: '1Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '1',
      },
      {
        date: new Date('2022, 9, 24'),
        text: '2Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '2',
      },
      {
        date: new Date('2022, 9, 25'),
        text: '3Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '3',
      },
      {
        date: new Date('2022, 9, 26'),
        text: '4Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '4',
      },
      {
        date: new Date('2022, 9, 27'),
        text: '5Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '5',
      },
    ],
    pinnedExisId: '3',
    bills: [10, 20],
    phoneNumber: '+375441234567',
  },
  {
    imgPath: ['/mocks/visitor2.png', '/mocks/small.png', '/mocks/small2.png'],
    name: '1Станиславов Станислав',
    status: 'moon',
    coincidentIds: [],
    id: '7',
    visits: [],
    exises: [
      {
        date: new Date('2022, 8, 23'),
        text: '1Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '1',
      },
      {
        date: new Date('2022, 9, 24'),
        text: '2Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '2',
      },
      {
        date: new Date('2022, 9, 25'),
        text: '3Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '3',
      },
      {
        date: new Date('2022, 9, 26'),
        text: '4Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '4',
      },
      {
        date: new Date('2022, 9, 27'),
        text: '5Often comes with people, orders chicken with vegetables, sometimes alcohol drinks',
        id: '5',
      },
    ],
    pinnedExisId: '3',
    bills: [10, 20],
    phoneNumber: '+375441234567',
  },
];
